# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    identifier: about
    weight: 10
  - name: Introduction
    parent: about
    url: introduction
    weight: 10  
  - name: Research Method
    parent: about
    url: methods
    weight: 20    
  - name: Research Questions
    parent: about
    url: questions
    weight: 30    
  - name: Partners
    url: partners
    weight: 30  
  - name: Team
    identifier: team
    weight: 20  
  - name: Advisory Board
    parent: team
    url: advisory
    weight: 20  
  - name: Researchers
    parent: team
    url: people
    weight: 10     
  - name: Outputs
    identifier: outputs
    weight: 40
  - name: Digital Archive
    parent: outputs
    url: digital
    weight: 10  
  - name: Exhibitions
    parent: outputs
    url: exhibitions
    weight: 20   
  - name: Documentaries
    parent: outputs
    url: documentaries
    weight: 30   
  - name: Publications
    parent: outputs
    url: publications
    weight: 40    
  - name: Contact
    url: contact
    weight: 50

    
